### ISSUE TITLE
Build Error By CMake

### ISSUE THREAD

**Issue by maobaoqi** [cheind/image-align#3]
I have a problem when I build this project using cmake. It shows that I need to have a OpenCVConfig.cmake file to point. But where is the suitable OpenCVConfig.cmake file? Could anyone help me? thanks!

**Comment by cheind** [comment]
The file can be found in the OpenCV directory inside the build directory (on Windows). Not sure where it is located on other platforms.

**Comment by YYimingWang** [comment]
The reason here maybe:
(1)you don't install opencv;
(2)you don't modify the path of OpenCVConfig in the code

**Comment by cheind** [comment]
On Windows you get OpenCVConfig.cmake  shipped with OpenCV within the build directory.
